
 DROP TABLE IF EXISTS users_details;
 DROP TABLE IF EXISTS courses_details;
 DROP TABLE IF EXISTS users_enrolled_courses_details;

create table users_details (userid bigint generated by default as identity, created_date timestamp, dob timestamp, email_id varchar(255), enabled integer, first_name varchar(255), last_name varchar(255), last_updated_date timestamp, login_password varchar(255), login_username varchar(255), mobile_no varchar(255), role varchar(255), primary key (userid));
create table courses_details (courseid integer generated by default as identity, course_name varchar(255), ref_url_text varchar(255), ref_url_video varchar(255), topic_name varchar(255), primary key (courseid));
create table users_enrolled_courses_details (id bigint generated by default as identity, login_username varchar(255), topic_name varchar(255), primary key (id));


--insert into users_details (userid, created_date, dob, email_id, enabled, first_name, last_name, last_updated_date, login_password, login_username, mobile_no, role) values (1, sysdate(), sysdate(), 'punya@gmail.com', 1, 'Punyasmruti', 'Nayak', sysdate(), 'punya', '$2a$10$g5fAs.BoSvFLeTwdRst/GuwWFI7Sr12LX4uBr0s8d2pBgzyMUq68e', '134567890','ROLE_USER')
--insert into users_details (userid, created_date, dob, email_id, enabled, first_name, last_name, last_updated_date, login_password, login_username, mobile_no, role) values (2, sysdate(), sysdate(), 'aswini@gmail.com', 1, 'Aswini', 'Kumar', sysdate(), 'aswini', '$2a$10$g5fAs.BoSvFLeTwdRst/GuwWFI7Sr12LX4uBr0s8d2pBgzyMUq68e', '987654310','ROLE_ADMIN')

--insert into courses_details (courseid, course_name, ref_url_text, ref_url_video, topic_name) values (1, 'Java', 'https://wwww.google.com', 'https://www.youtube.com', 'Core Java');
--insert into courses_details (courseid, course_name, ref_url_text, ref_url_video, topic_name) values (2, 'Java', 'https://wwww.google.com', 'https://www.youtube.com', 'Advanced Java');

--insert into users_enrolled_courses_details (id, login_username, topic_name) values (1, 'punya', 'Core Java');

commit;
